export type Lang = "en" | "ru"

export type Stranger = {
  id: string
  interests: string[]
  opener: Record<Lang, string>
  replies: Record<Lang, string[]>
}

export type ReactionDef = { sym: string; label: string }
export type ThemeDef = { id: string; label: string }

export const GLYPHS = [
  "◊", "◈", "◉", "◎", "△", "▽", "☉", "◐", "◑", "⬡",
  "⬢", "✦", "✧", "◇", "■", "□", "●", "○", "☐", "✕",
]

export const INTERESTS = [
  "philosophy",
  "design",
  "code",
  "music",
  "film",
  "science",
  "books",
  "gaming",
  "travel",
  "food",
  "art",
  "tech",
]

export const THEMES: ThemeDef[] = [
  { id: "mono", label: "Mono" },
  { id: "sepia", label: "Sepia" },
  { id: "night", label: "Night" },
  { id: "terminal", label: "Terminal" },
  { id: "red", label: "Red" },
  { id: "pink", label: "Pink" },
  { id: "acid", label: "Acid" },
]

export const REACTIONS: ReactionDef[] = [
  { sym: "+", label: "agree" },
  { sym: "?", label: "confused" },
  { sym: "!", label: "wow" },
  { sym: "✓", label: "seen" },
  { sym: "✕", label: "disagree" },
  { sym: "♡", label: "love" },
]

export const STRANGERS: Stranger[] = [
  {
    id: "2948",
    interests: ["design", "film"],
    opener: {
      en: "hey. another ghost in the machine?",
      ru: "привет. ещё один призрак в машине?",
    },
    replies: {
      en: [
        "so what brings you to the quiet side of the internet?",
        "i like how this place looks. no ads, no faces, no echo.",
        "do you think anonymity changes what people say, or only how?",
        "favorite film that nobody else you know has seen?",
        "i keep thinking the web used to feel smaller.",
        "name a font you'd get tattooed. im serious.",
      ],
      ru: [
        "так что тебя сюда привело?",
        "мне нравится как тут тихо. ни лиц, ни рекламы, ни эха.",
        "думаешь анонимность меняет что люди говорят, или только как?",
        "последний фильм, который тебя задел?",
        "мне кажется раньше интернет казался меньше и теплее.",
        "какой шрифт ты бы набил тату? серьёзно.",
      ],
    },
  },
  {
    id: "1827",
    interests: ["code", "science"],
    opener: {
      en: "hi. you look like a person with opinions about monospace fonts.",
      ru: "привет. ты похож на человека с мнением о моноширинных шрифтах.",
    },
    replies: {
      en: [
        "are you debugging life or just hanging out?",
        "what's the last bug that actually made you laugh?",
        "vim or emacs or we pretend neither exists?",
        "i think the universe is eventually consistent at best.",
        "explain your favorite algorithm like im a stranger on the internet.",
      ],
      ru: [
        "ты дебажишь жизнь или просто завис?",
        "какой последний баг реально заставил тебя смеяться?",
        "vim, emacs или делаем вид что ничего этого нет?",
        "по-моему вселенная в лучшем случае eventually consistent.",
        "расскажи свой любимый алгоритм как незнакомцу.",
      ],
    },
  },
  {
    id: "4091",
    interests: ["philosophy", "books"],
    opener: {
      en: "if this session ends, does this conversation have happened?",
      ru: "если сессия закроется, была ли эта беседа?",
    },
    replies: {
      en: [
        "what are you reading that you can't stop thinking about?",
        "do you believe anonymity is closer to truth or to lying?",
        "if you had to pick one unread book to defend, which?",
        "i'm convinced loneliness is the modern default state.",
        "name one idea you'd die on the hill for.",
      ],
      ru: [
        "что сейчас читаешь и не можешь перестать думать?",
        "анонимность ближе к правде или ко лжи, как считаешь?",
        "если надо защитить одну непрочитанную книгу — какая?",
        "одиночество, по-моему, дефолт современного человека.",
        "какую идею ты готов защищать до последнего?",
      ],
    },
  },
  {
    id: "7312",
    interests: ["music", "travel"],
    opener: {
      en: "what's on in your headphones right now?",
      ru: "что у тебя сейчас в наушниках?",
    },
    replies: {
      en: [
        "i think cities have soundtracks. mine is mostly rain.",
        "best city to get lost in at 3am?",
        "a song you'd play for someone to explain yourself.",
        "i travel to forget where i'm from for a week.",
        "live recording or studio? defend your answer.",
      ],
      ru: [
        "мне кажется у городов есть саундтреки. мой — это в основном дождь.",
        "лучший город чтобы потеряться в 3 ночи?",
        "песня, которой ты бы объяснил(а) себя кому-то?",
        "я путешествую чтобы на неделю забыть откуда я.",
        "лайв или студийная запись? защити ответ.",
      ],
    },
  },
  {
    id: "5604",
    interests: ["gaming", "food"],
    opener: {
      en: "if we had a lobby, what would we be queuing for?",
      ru: "если бы у нас было лобби — в какую игру мы бы встали?",
    },
    replies: {
      en: [
        "weirdest thing you cooked this month?",
        "dark souls or cozy farming sim, pick your soul.",
        "food that ruins all others for you?",
        "i swear single player games have the best dialogue writing now.",
        "you'd rather beat a boss or finish a long recipe?",
      ],
      ru: [
        "самая странная штука которую ты готовил(а) в этом месяце?",
        "dark souls или уютная ферма — что ближе?",
        "еда после которой всё остальное кажется пресным?",
        "клянусь, лучшие диалоги сейчас в сингл-плеере.",
        "что ближе: победить босса или довести до конца сложный рецепт?",
      ],
    },
  },
  {
    id: "3859",
    interests: ["design", "music", "art"],
    opener: {
      en: "i keep trying to make things look less like 2012. some help?",
      ru: "всё пытаюсь чтобы штуки выглядели не как 2012. поможешь?",
    },
    replies: {
      en: [
        "swiss, brutalist, editorial — pick one and tell me why.",
        "a color you hate at work but love at home?",
        "what's the smallest detail you obsess over?",
        "type system you'd restart your career on.",
        "ever make something you didn't want anyone to see?",
      ],
      ru: [
        "swiss, brutalist, editorial — выбери один и скажи почему.",
        "цвет который ненавидишь на работе, но любишь дома?",
        "на какой мелочи ты залипаешь дольше всего?",
        "типографика ради которой перезапустил бы карьеру.",
        "делал(а) когда-то что-то что никому не хотел(а) показывать?",
      ],
    },
  },
]

export const I18N: Record<Lang, Record<string, string>> = {
  en: {
    brandTag: "Encrypted · Ephemeral · No sign-up",
    home: "Home",
    kicker01: "Session",
    heroTitle: "Talk to <em>your circle</em>.",
    heroSub:
      "Encrypted chat for friends, partners and teams. No sign-up, no cookies, no history. Close the tab — nothing remains: not on the server, not in memory, not anywhere.",
    sessionId: "Session ID",
    reroll: "Regenerate",
    legendFree: "Zero sign-up",
    legendEph: "Ephemeral",
    legendE2E: "End-to-end",
    joinByCode: "Join by code",
    pressEnterJoin: "Press ↵ to join",
    codePlaceholder: "XXX · XXX",
    joinHint: "Paste invite code or type @handle",
    badCode: "Not a valid invite code or handle",
    enter: "Enter",
    findStranger: "Private only",
    findStrangerDesc: "Random match was removed because it weakened end-to-end encryption. Use invite codes instead.",
    create: "Create",
    newRoom: "New room",
    newRoomDesc: "Generate a code, share it, keep the room open for up to 24 hours.",
    online: "Online now",
    newConnections: "New / hour",
    messagesPerMin: "Msgs / min",
    avgDuration: "Avg session",
    connected: "Connected to",
    roomCode: "Room code",
    next: "Next",
    tweaks: "Tweaks",
    sessionLbl: "Session",
    you: "You",
    activePeers: "Active",
    interests: "Interests",
    encrypted: "E2E encrypted",
    messagesGone:
      "Messages vanish when the session closes. Nothing is logged server-side.",
    connectedTo: "Connected",
    report: "Report",
    disconnect: "Disconnect",
    typing: "typing",
    strangerTyping: "stranger typing",
    online2: "online",
    pressEnter: "press ↵ to send · shift+↵ newline",
    placeholder: "Say something private…",
    theme: "Theme",
    corners: "Corners",
    sharp: "Sharp",
    soft: "Soft",
    round: "Round",
    bubble: "Bubble",
    flat: "Flat",
    brackets: "Brackets",
    stamped: "Stamped",
    density: "Density",
    compact: "Compact",
    cozy: "Cozy",
    loose: "Loose",
    fontPair: "Font pair",
    editorial: "Editorial",
    grotesk: "Grotesk",
    mono: "Mono",
    language: "Language",
    createTitle: "Create",
    newRoomHero: "New <em>room</em>.",
    newRoomSubtitle:
      "Two to fifty people. End-to-end encrypted. Self-destructs when the timer runs out.",
    tabRoom: "Room",
    tabChannel: "Channel",
    tabGroup: "Group",
    soon: "Soon",
    comingSoonFooter: "— Channels & groups are coming soon. Private rooms work fully today. —",
    maxUsers: "Max users",
    selfDestruct: "Self-destruct",
    forgeRoom: "Forge encrypted room",
    saving: "Creating…",
    yourPrivateCode: "Your <em>private</em> code.",
    invitePreamble:
      "Share this with the person you want to talk to. Anyone with the code can enter the room — the key lives inside it.",
    copyCode: "Copy code",
    copyLink: "Copy link",
    copied: "Copied",
    enterRoom: "Enter room",
    inviteWarnLabel: "Warning",
    inviteWarnBody:
      "Only share with people you trust. The code IS the key — if someone else has it, they can read everything.",
    inviteCode: "Invite code",
    fullLink: "Full link",
  },
  ru: {
    brandTag: "Анонимно · Без аккаунтов · Без логов",
    home: "На главную",
    kicker01: "Установка сессии",
    heroTitle: "Говори со <em>своими</em>.",
    heroSub:
      "Шифрованный чат для друзей, партнёров и команд. Без регистрации, cookies и истории. Закрыл вкладку — ничего не осталось: ни на сервере, ни в памяти.",
    sessionId: "ID сессии",
    reroll: "Сгенерировать заново",
    legendFree: "Без регистрации",
    legendEph: "Эфемерно",
    legendE2E: "End-to-end",
    joinByCode: "Войти по коду",
    pressEnterJoin: "Нажми ↵ чтобы войти",
    codePlaceholder: "XXX · XXX",
    joinHint: "Вставь код приглашения или введи @handle",
    badCode: "Не похоже на код приглашения или handle",
    enter: "Войти",
    findStranger: "Только приватно",
    findStrangerDesc:
      "Случайный матч убран: он ослаблял end-to-end шифрование. Используй invite code.",
    create: "Создать",
    newRoom: "Новая комната",
    newRoomDesc:
      "Сгенерировать код, поделиться им, держать комнату открытой до 24 часов.",
    online: "Онлайн сейчас",
    newConnections: "Новых / час",
    messagesPerMin: "Сообщ / мин",
    avgDuration: "Ср. сессия",
    connected: "Подключён к",
    roomCode: "Код комнаты",
    next: "Дальше",
    tweaks: "Настройки",
    sessionLbl: "Сессия",
    you: "Ты",
    activePeers: "Активные",
    interests: "Интересы",
    encrypted: "E2E шифрование",
    messagesGone:
      "Сообщения исчезают с закрытием сессии. Ничего не пишется на сервер.",
    connectedTo: "Подключён",
    report: "Пожаловаться",
    disconnect: "Отключиться",
    typing: "печатает",
    strangerTyping: "собеседник печатает",
    online2: "онлайн",
    pressEnter: "нажми ↵ чтобы отправить · shift+↵ новая строка",
    placeholder: "Скажи что-нибудь приватное…",
    theme: "Тема",
    corners: "Углы",
    sharp: "Острые",
    soft: "Мягкие",
    round: "Круглые",
    bubble: "Пузырь",
    flat: "Плоский",
    brackets: "Скобки",
    stamped: "Штамп",
    density: "Плотность",
    compact: "Плотно",
    cozy: "Уютно",
    loose: "Просторно",
    fontPair: "Шрифты",
    editorial: "Editorial",
    grotesk: "Grotesk",
    mono: "Mono",
    language: "Язык",
    createTitle: "Создать",
    newRoomHero: "Новая <em>комната</em>.",
    newRoomSubtitle:
      "От двух до пятидесяти человек. Сквозное шифрование. Самоуничтожение по таймеру.",
    tabRoom: "Комната",
    tabChannel: "Канал",
    tabGroup: "Группа",
    soon: "Скоро",
    comingSoonFooter:
      "— Каналы и публичные группы появятся позже. Приватные комнаты работают уже сейчас. —",
    maxUsers: "Макс. людей",
    selfDestruct: "Самоуничтожение",
    forgeRoom: "Создать зашифрованную комнату",
    saving: "Создание…",
    yourPrivateCode: "Твой <em>приватный</em> код.",
    invitePreamble:
      "Поделись этим с тем, с кем хочешь говорить. У любого с этим кодом есть доступ — ключ внутри кода.",
    copyCode: "Скопировать код",
    copyLink: "Скопировать ссылку",
    copied: "Скопировано",
    enterRoom: "Войти в комнату",
    inviteWarnLabel: "Важно",
    inviteWarnBody:
      "Делись только с теми, кому доверяешь. Код = ключ шифрования: у кого он есть — у того есть доступ ко всем сообщениям.",
    inviteCode: "Код приглашения",
    fullLink: "Полная ссылка",
  },
}
